version: '3'

services:
    dhcpd:
        build: {{maindir}}dhcp/{{nombrecliente}}/
        container_name: dhcpd
        restart: unless-stopped
        networks:
            {{networkname}}:
                ipv4_address: {{ipcontenedor}}
        volumes:
            - {{maindir}}dhcp/{{nombrecliente}}/dhcpd.conf:/etc/dhcp/dhcpd.conf
        ports:
         - 67:67             
networks:
    {{networkname}}:
        external: true